=== maesche/calendar/xml/dtd/application.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT application (page-title+, months+, days+, information-title+, calendar-choice+, go-to+)>
<!ELEMENT page-title (#PCDATA)>

<!ELEMENT months (month+)>
<!ELEMENT month (full+, short+)>

<!ELEMENT days (day+)>
<!ELEMENT day (full+, short+)>


<!ELEMENT full (#PCDATA)>
<!ELEMENT short (#PCDATA)>

<!ELEMENT information-title (#PCDATA)>
<!ELEMENT calendar-choice (#PCDATA)>
<!ELEMENT go-to (#PCDATA)>

<!ATTLIST application lang CDATA #REQUIRED>

=== maesche/calendar/xml/lang/en/application.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE application SYSTEM "../../dtd/application.dtd">
<application lang="en">
    <page-title>FBM room reservation</page-title>
    <months>
        <month>
            <full>January</full>
            <short>Jan</short>
        </month>
        <month>
            <full>February</full>
            <short>Feb</short>
        </month>
        <month>
            <full>March</full>
            <short>Mar</short>
        </month>
        <month>
            <full>April</full>
            <short>Apr</short>
        </month>
        <month>
            <full>May</full>
            <short>May</short>
        </month>
        <month>
            <full>June</full>
            <short>June</short>
        </month>
        <month>
            <full>July</full>
            <short>July</short>
        </month>
        <month>
            <full>August</full>
            <short>Aut</short>
        </month>
        <month>
            <full>September</full>
            <short>Sep</short>
        </month>
        <month>
            <full>October</full>
            <short>Oct</short>
        </month>
        <month>
            <full>November</full>
            <short>Nov</short>
        </month>
        <month>
            <full>December</full>
            <short>Dec</short>
        </month>
    </months>
    <days>
        <day>
            <full>Monday</full>
            <short>Mon</short>
        </day>
        <day>
            <full>Tuesday</full>
            <short>Tue</short>
        </day>
        <day>
            <full>Wednesday</full>
            <short>Wed</short>
        </day>
        <day>
            <full>Thursday</full>
            <short>Thu</short>
        </day>
        <day>
            <full>Friday</full>
            <short>Fri</short>
        </day>
        <day>
            <full>Saturday</full>
            <short>Sat</short>
        </day>
        <day>
            <full>Sunday</full>
            <short>Sun</short>
        </day>
    </days>
    <information-title>Informations</information-title>
    <calendar-choice>Choose calendar</calendar-choice>
    <go-to>Go to</go-to>
</application>

=== maesche/calendar/xml/lang/fr/application.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE application SYSTEM "../../dtd/application.dtd">
<application lang="fr">
    <page-title>Réservation des salles de la FBM</page-title>
    <months>
        <month>
            <full>Janvier</full>
            <short>Jan</short>
        </month>
        <month>
            <full>Février</full>
            <short>Fév</short>
        </month>
        <month>
            <full>Mars</full>
            <short>Mar</short>
        </month>
        <month>
            <full>Avril</full>
            <short>Avr</short>
        </month>
        <month>
            <full>Mai</full>
            <short>Mai</short>
        </month>
        <month>
            <full>Juin</full>
            <short>Juin</short>
        </month>
        <month>
            <full>Juillet</full>
            <short>Juil</short>
        </month>
        <month>
            <full>Août</full>
            <short>Août</short>
        </month>
        <month>
            <full>Septembre</full>
            <short>Sep</short>
        </month>
        <month>
            <full>Octobre</full>
            <short>Oct</short>
        </month>
        <month>
            <full>Novembre</full>
            <short>Nov</short>
        </month>
        <month>
            <full>Décembre</full>
            <short>Déc</short>
        </month>
    </months>
    <days>
        <day>
            <full>Lundi</full>
            <short>Lun</short>
        </day>
        <day>
            <full>Mardi</full>
            <short>Mar</short>
        </day>
        <day>
            <full>Mercredi</full>
            <short>Mer</short>
        </day>
        <day>
            <full>Jeudi</full>
            <short>Jeu</short>
        </day>
        <day>
            <full>Vendredi</full>
            <short>Ven</short>
        </day>
        <day>
            <full>Samedi</full>
            <short>Sam</short>
        </day>
        <day>
            <full>Dimanche</full>
            <short>Dim</short>
        </day>
    </days>
    <information-title>Informations</information-title>
    <calendar-choice>Choix du calendrier</calendar-choice>
    <go-to>Aller à</go-to>
</application>

=== maesche/calendar/xml/lang/ja/application.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE application SYSTEM "../../dtd/application.dtd">
<application lang="ja">
    <page-title>FBM ルーム予約システム</page-title>
    <months>
        <month>
            <full>1 月</full>
            <short>1 月</short>
        </month>
        <month>
            <full>2 月</full>
            <short>2 月</short>
        </month>
        <month>
            <full>3 月</full>
            <short>3 月</short>
        </month>
        <month>
            <full>4 月</full>
            <short>4 月</short>
        </month>
        <month>
            <full>5 月</full>
            <short>5 月</short>
        </month>
        <month>
            <full>6 月</full>
            <short>6 月</short>
        </month>
        <month>
            <full>7 月</full>
            <short>7 月</short>
        </month>
        <month>
            <full>8 月</full>
            <short>8 月</short>
        </month>
        <month>
            <full>9 月</full>
            <short>9 月</short>
        </month>
        <month>
            <full>10 月</full>
            <short>10 月</short>
        </month>
        <month>
            <full>11 月</full>
            <short>11 月</short>
        </month>
        <month>
            <full>12 月</full>
            <short>12 月</short>
        </month>
    </months>
    <days>
        <day>
            <full>月曜日</full>
            <short>月</short>
        </day>
        <day>
            <full>火曜日</full>
            <short>火</short>
        </day>
        <day>
            <full>水曜日</full>
            <short>水</short>
        </day>
        <day>
            <full>木曜日</full>
            <short>木</short>
        </day>
        <day>
            <full>金曜日</full>
            <short>金</short>
        </day>
        <day>
            <full>土曜日</full>
            <short>土</short>
        </day>
        <day>
            <full>日曜日</full>
            <short>日</short>
        </day>
    </days>
    <information-title>お知らせ</information-title>
    <calendar-choice>カレンダー</calendar-choice>
    <go-to>日付</go-to>
</application>
