=== maesche/calendar/xml/dtd/event.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT event (messages+, new+, edit+, save+, delete+, cancel+, user+, title+, date+, whole-day+, start+, end+, repeat+, description+)>

<!ELEMENT messages (error+, check+, repeat-info+, other-user+)>
<!ELEMENT error (time+)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT check (#PCDATA)>
<!ELEMENT repeat-info (#PCDATA)>
<!ELEMENT other-user (#PCDATA)>

<!ELEMENT new (#PCDATA)>
<!ELEMENT edit (#PCDATA)>
<!ELEMENT save (#PCDATA)>
<!ELEMENT user (#PCDATA)>
<!ELEMENT delete (#PCDATA)>
<!ELEMENT cancel (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT whole-day (#PCDATA)>
<!ELEMENT start (#PCDATA)>
<!ELEMENT end (#PCDATA)>
<!ELEMENT description (#PCDATA)>

<!ELEMENT repeat (title+, never+, daily+, weekly+, half-monthly+, monthly+, yearly+, until+)>
<!ELEMENT never (#PCDATA)>
<!ELEMENT daily (#PCDATA)>
<!ELEMENT weekly (#PCDATA)>
<!ELEMENT half-monthly (#PCDATA)>
<!ELEMENT monthly (#PCDATA)>
<!ELEMENT yearly (#PCDATA)>
<!ELEMENT until (#PCDATA)>

<!ATTLIST event lang CDATA #REQUIRED>

=== maesche/calendar/xml/lang/ja/event.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE event SYSTEM "../../dtd/event.dtd">
<event lang="ja">
    <messages>
        <error>
            <time>時間のエラーがあります。</time>
            <unavailable>The following dates bellow are unavailable.</unavailable>
        </error>
        <check>赤い部分の情報を確かめてください。</check>
        <repeat-info>このイベントは繰り返し指定です。すべての情報は変更されます。</repeat-info>
        <other-user>このイベントは編集ができません。アカウント主は  </other-user>
    </messages>
    <new>イベントを作る</new>
    <edit>イベントの編集</edit>
    <save>保存</save>
    <delete>消去</delete>
    <cancel>取り消し</cancel>
    <user>所有者</user>
    <title>題名</title>
    <date>日付</date>
    <whole-day>終日</whole-day>
    <start>開始</start>
    <end>終了</end>
    <repeat>
        <title>繰り返し</title>
        <never>なし</never>
        <daily>毎日</daily>
        <weekly>毎週</weekly>
        <half-monthly>二週間に一回</half-monthly>
        <monthly>毎月</monthly>
        <yearly>毎年</yearly>
        <until>繰り返し終了</until>
    </repeat>
    <description>メモ</description>
</event>

=== maesche/calendar/xml/lang/fr/event.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE event SYSTEM "../../dtd/event.dtd">
<event lang="fr">
    <messages>
        <error>
            <time>L'heure de fin doit être supérieure à l'heure de début.</time>
            <unavailable>Les plages horaires ci-dessous sont indisponibles.</unavailable>
        </error>
        <check>Veuillez vérifier les champs en rouge</check>
        <repeat-info>Cet événement est répétitif. Toutes les occurences seront modifiées.</repeat-info>
        <other-user>Cet événement ne peut pas être modifié car il appartient à quelqu'un d'autre. </other-user>
    </messages>
    <new>Créer un événement</new>
    <edit>Modifier un événement</edit>
    <save>Enregistrer</save>
    <delete>Supprimer</delete>
    <cancel>Annuler</cancel>
    <user>Propriétaire</user>
    <title>Titre</title>
    <date>Date</date>
    <whole-day>Jour entier</whole-day>
    <start>Début</start>
    <end>Fin</end>
    <repeat>
        <title>Répéter</title>
        <never>Jamais</never>
        <daily>Chaque jour</daily>
        <weekly>Chaque semaine</weekly>
        <half-monthly>Toutes les deux semaines</half-monthly>
        <monthly>Chaque mois</monthly>
        <yearly>Chaque année</yearly>
        <until>Jusqu'au</until>
    </repeat>
    <description>Description</description>
</event>

=== maesche/calendar/xml/lang/en/event.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE event SYSTEM "../../dtd/event.dtd">
<event lang="en">
    <messages>
        <error>
            <time>The end time must be bigger than the start time</time>
            <unavailable>The following dates bellow are unavailable.</unavailable>
        </error>
        <check>Please verify the fields in red.</check>
        <repeat-info>This is a repeating event. Every entry will be modified.</repeat-info>
        <other-user>This event can not be modified because it belongs to an other user.</other-user>
    </messages>
    <new>New event</new>
    <edit>Edit event</edit>
    <save>Save</save>
    <delete>Delete</delete>
    <cancel>Cancel</cancel>
    <user>Owner</user>
    <title>Title</title>
    <date>Date</date>
    <whole-day>Whole day</whole-day>
    <start>Start</start>
    <end>End</end>
    <repeat>
        <title>Repeat</title>
        <never>Never</never>
        <daily>Every day</daily>
        <weekly>Every week</weekly>
        <half-monthly>Every two weeks</half-monthly>
        <monthly>Every month</monthly>
        <yearly>Every year</yearly>
        <until>Until</until>
    </repeat>
    <description>Description</description>
</event>
